[package]
name = "swayr"
version = "0.0.1"
authors = ["Tassilo Horn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
clap = "3.0.0-beta.2"
users = "0.11.0"
