[package]
name = "swayr"
version = "0.1.1"
description = "A wofi-based LRU window-switcher (and more) for the sway window manager"
homepage = "https://sr.ht/~tsdh/swayr/"
repository = "https://git.sr.ht/~tsdh/swayr"
authors = ["Tassilo Horn <tsdh@gnu.org>"]
license = "GPL-3.0+"
edition = "2018"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
clap = "3.0.0-beta.2"
users = "0.11.0"
swayipc = "2.7.2"