max_width = 80
newline_style = "Unix"
use_try_shorthand = true
use_field_init_shorthand = true
edition = "2021"
# The below would be nice but are unstable right now...
#version = "Two"
#format_strings = true
#reorder_impl_items = true
#group_imports = "StdExternalCrate"
# format_code_in_doc_comments = true
